### ISSUE TITLE
Dados atualizados

### ISSUE THREAD

**Issue by ThiagoGrabe** [dfalbel/ons#1]
Gostaria dos dados atualizados da ONS, caso seja possível. AInda é possível obter esses dados? Tentei pelo site da ONS e não consegui. Obrigado!

**Comment by dfalbel** [comment]
Provavelmente meu código não funciona mais :( Mas ainda deve ser possível

**Comment by dfalbel** [comment]
Eles mudaram o sisteminha, mas ainda tem aqui: http://www.ons.org.br/Paginas/resultados-da-operacao/historico-da-operacao/carga_energia.aspx
